Add build option for Android (#30)
* Android API as parameter, remove useless code
* quick fix for API >18, <21

diff --git a/ndk-gcc b/ndk-gcc
--- a/ndk-gcc
+++ b/ndk-gcc
@@ -3,8 +3,9 @@
 
 if [ -z "${NDK}" ]; then
 	NDK=~/Downloads/android-ndk-r10e
+	echo "Using ${NDK} as NDK path."
 	if [ ! -d "${NDK}" ]; then
-		echo "Invalid path in NDK environment"
+		echo "Invalid path in NDK environment, please change me."
 		exit 1
 	fi
 fi
@@ -15,22 +16,12 @@ else
 	ARCH=mips
 	ARCH=x86
 	ARCH=arm
+	ARCH=x86_64
+	ARCH=aarch64
 fi
 
 ANDROID_API_LEVEL=$1
-shift 
-
-case "${ANDROID_API_LEVEL}" in
-kk|kitkat)
-	ANDROID_API_LEVEL=19
-	;;
-ll|lollipop)
-	ANDROID_API_LEVEL=21
-	;;
-*)
-	ANDROID_API_LEVEL=19
-	;;
-esac
+shift
 
 echo "Using NDK ${NDK}"
 echo "Using NDK_ARCH ${NDK_ARCH} -> ${ARCH}"
@@ -41,8 +32,6 @@ echo "Using ANDROID_API_LEVEL ${ANDROID_API_LEVEL}"
 PROGDIR="$(dirname "$0")"
 PROGDIR="$(cd "$PROGDIR" && pwd)"
 
-# shellcheck disable=SC2019
-# shellcheck disable=SC2018
 OS="$(uname | tr 'A-Z' 'a-z')"
 [ "${OS}" = macos ] && OS=darwin
 
@@ -76,30 +65,30 @@ x86)
 		NDKPFX=i686-linux-android
 	fi
 	;;
+x86_64)
+	NDKPFX=x86_64-android-linux
+	${NDKPFX}-gcc 2>/dev/null
+	if [ $? -gt 1 ]; then
+		NDKPFX=x86_64-linux-android
+	fi
+	;;
 esac
-
-if [ -d "${PROGDIR}/platforms/android-L/arch-${ARCH}" ]; then
-	ANDROID_API_LEVEL=L
-fi
 
 PROGDIR=${NDK}
 PLATFORM=android-${ANDROID_API_LEVEL}
 PLATFORM_ROOT=${PROGDIR}/platforms/${PLATFORM}/arch-${ARCH2}
 PLATFORM_PATH=${PLATFORM_ROOT}/usr
-# shellcheck disable=SC2010
+
 NDK_BINS=$(ls "${PROGDIR}"/toolchains/*/prebuilt/"${OS}"*/bin |grep prebuilt | grep "/${ARCH}-" |sort |tail -n 1)
-# shellcheck disable=SC2010
 [ -z "${NDK_BINS}" ] && \
 NDK_BINS=$(ls "${PROGDIR}"/toolchains/*/prebuilt/"${OS}"*/bin |grep prebuilt | grep "/${ARCH}" |sort |tail -n 1)
-#echo "ls ${PROGDIR}/toolchains/*/prebuilt/linux*/bin |grep prebuilt | grep "/${ARCH}-" |sort |tail -n 1"
-#echo NDKBINS=${NDK_BINS}
+
 if [ -z "${NDK_BINS}" ]; then
 	echo "Cant find NDK_BINS"
 	exit 1
 fi
 CFLAGS="${CFLAGS} --sysroot=${PLATFORM_ROOT}"
-CFLAGS="${CFLAGS} -I${PLATFORM_PATH}/include"
-CFLAGS="${CFLAGS} -fPIC -fPIE"
+CFLAGS="${CFLAGS} -fPIC -fPIE -pie"
 
 case "${ARCH}" in
 mips64)
@@ -110,14 +99,8 @@ mips64)
 	;;
 esac
 
-#LDFLAGS="${LDFLAGS} -nostdlib"
-#LDFLAGS="${LDFLAGS} -lc -ldl"
-#LDFLAGS="${LDFLAGS} -Wl,-dynamic-linker=/system/bin/linker"
-
 LDFLAGS="${LDFLAGS} --sysroot=${PLATFORM_ROOT}"
-#if [ -z "`echo $*" | grep shared`" ]; then
-#LDFLAGS="${LDFLAGS} ${PLATFORM_PATH}/lib/crtbegin_dynamic.o"
-#fi
+
 CC="${NDKPFX}-gcc"
 AR="${NDKPFX}-ar"
 EXT_SO=so
@@ -125,7 +108,5 @@ EXT_SO=so
 export PATH="${NDK_BINS}:$PATH"
 export EXT_SO AR CC CFLAGS LDFLAGS PATH
 
-#shellcheck disable=SC2048
-#shellcheck disable=SC2086
 echo ${CC} ${LDFLAGS} ${CFLAGS} $*
 ${CC} ${LDFLAGS} ${CFLAGS} $*
